name: Deploy Front to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone código do GitHub
      uses: actions/checkout@v3

    - name: Deploy via SSH na VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/WhatsWrappedFront
          git pull origin main
          npm install
          npm run build
          pm2 restart zap-love-front


